---
name: Build fastfetch for MiSTer
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**'
  workflow_dispatch:

permissions: write-all

jobs:
  Build:
    runs-on: ubuntu-latest
    env:
      FASTFETCH_VERSION: "2.62.1"

    steps:
      - uses: actions/checkout@v4

      - name: Check version cache
        id: cache-check
        uses: actions/cache@v4
        with:
          path: /tmp/build-status.txt
          key: fastfetch-${{ env.FASTFETCH_VERSION }}

      - name: Install apt-get utilities
        if: steps.cache-check.outputs.cache-hit != 'true' ||
          github.event_name == 'pull_request'
        run: >
          sudo apt update &&
          sudo apt-get install -y -qq
          binfmt-support
          build-essential
          cmake
          pkg-config
          gcc-arm-linux-gnueabihf
          qemu-user-static
          # autoconf
          # curl
          # git
          # gcc
          # make
          # qemu-user
          # sharutils
          # u-boot-tools
          # g++-arm-linux-gnueabihf

      - name: Build fastfetch
        if: steps.cache-check.outputs.cache-hit != 'true' ||
          github.event_name == 'pull_request'
        env:
          SOURCE_DATE_EPOCH: "0"
        run: .github/build.sh

      - name: Update cache version
        if: steps.cache-check.outputs.cache-hit != 'true' &&
          github.ref == 'refs/heads/main'
        run: >
          echo "fastfetch-${{ env.FASTFETCH_VERSION }}" > /tmp/build-status.txt

      - name: Commit and push changes
        if: steps.cache-check.outputs.cache-hit != 'true' &&
          github.ref == 'refs/heads/main'
        uses: devops-infra/action-commit-push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          commit_message: Updated Scripts directory

      - name: Build Custom Database for MiSTer Downloader
        if: github.ref == 'refs/heads/main'
        run: >
          sudo chown -R runner .git ;
          set -o pipefail
          && curl --fail --location https://raw.githubusercontent.com/theypsilon/Downloader_DB-Template_MiSTer/main/.github/build_db.py
          | python3 -
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
