---
name: Build fastfetch for MiSTer
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**'
  workflow_dispatch:

permissions: write-all

jobs:
  Build:
    runs-on: ubuntu-latest
    env:
      FASTFETCH_VERSION: "2.64.1"

    steps:
      - uses: actions/checkout@v4

      - name: Check version cache
        id: cache-check
        uses: actions/cache@v4
        with:
          path: /tmp/build-status.txt
          key: fastfetch-${{ env.FASTFETCH_VERSION }}

      - name: Install apt-get utilities
        if: steps.cache-check.outputs.cache-hit != 'true' ||
          github.event_name == 'pull_request'
        run: >
          sudo apt update &&
          sudo apt-get install -y -qq
          binfmt-support
          build-essential
          cmake
          gcc-arm-linux-gnueabihf
          pkg-config
          qemu-user-static

      - name: Build
        if: steps.cache-check.outputs.cache-hit != 'true' ||
          github.event_name == 'pull_request'
        env:
          SOURCE_DATE_EPOCH: "0"
        run: |
          set -euo pipefail
          STARTDIR="$PWD"
          cd /tmp
          wget -q "https://github.com/fastfetch-cli/fastfetch/archive/refs/tags/${FASTFETCH_VERSION}.tar.gz"
          tar xf "${FASTFETCH_VERSION}.tar.gz"
          cd "fastfetch-${FASTFETCH_VERSION}"
          mkdir build
          cd build
          cmake \
            -DCMAKE_C_COMPILER=arm-linux-gnueabihf-gcc \
            -DCMAKE_SYSTEM_NAME=Linux \
            -DCMAKE_SYSTEM_PROCESSOR=armv7l \
            -DCMAKE_EXE_LINKER_FLAGS="-static" \
            -DBUILD_SHARED_LIBS=OFF \
            -DPACKAGES_REMOVE_DISABLED=ON \
            -DMODULE_DISABLE_BATTERY=ON \
            -DMODULE_DISABLE_BRIGHTNESS=ON \
            -DMODULE_DISABLE_BTRFS=ON \
            -DMODULE_DISABLE_CAMERA=ON \
            -DMODULE_DISABLE_CODEC=ON \
            -DMODULE_DISABLE_DE=ON \
            -DMODULE_DISABLE_MEDIA=ON \
            -DMODULE_DISABLE_MONITOR=ON \
            -DMODULE_DISABLE_OPENCL=ON \
            -DMODULE_DISABLE_OPENGL=ON \
            -DMODULE_DISABLE_PACKAGES=ON \
            -DMODULE_DISABLE_PLAYER=ON \
            -DMODULE_DISABLE_POWERADAPTER=ON \
            -DMODULE_DISABLE_TPM=ON \
            -DMODULE_DISABLE_VULKAN=ON \
            -DMODULE_DISABLE_WALLPAPER=ON \
            -DMODULE_DISABLE_WM=ON \
            -DMODULE_DISABLE_WMTHEME=ON \
            -DMODULE_DISABLE_ZPOOL=ON \
            ..

          cmake --build . --target fastfetch

          ./fastfetch && cp -v "$(find . -type f -name fastfetch)" \
            "${STARTDIR}/Scripts/.config/fastfetch"
          ./fastfetch --version
          ./fastfetch --list-features
          ./fastfetch --list-modules

      - name: Update cache version
        if: steps.cache-check.outputs.cache-hit != 'true' &&
          github.ref == 'refs/heads/main'
        run: >
          echo "fastfetch-${{ env.FASTFETCH_VERSION }}" > /tmp/build-status.txt

      - name: Commit and push changes
        if: steps.cache-check.outputs.cache-hit != 'true' &&
          github.ref == 'refs/heads/main'
        uses: devops-infra/action-commit-push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          commit_message: Updated Scripts directory

      - name: Build Custom Database for MiSTer Downloader
        if: github.ref == 'refs/heads/main'
        run: >
          sudo chown -R runner .git ;
          set -o pipefail
          && curl --fail --location https://raw.githubusercontent.com/theypsilon/Downloader_DB-Template_MiSTer/main/.github/build_db.py
          | python3 -
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
