---
name: Build fastfetch for MiSTer
on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions: write-all

jobs:
  build_fastfetch:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install apt-get utilities
      run: >
        sudo apt update &&
        sudo apt-get install -y -qq
        binfmt-support
        qemu-user-static
        autoconf
        build-essential
        curl
        gcc
        git
        make
        cmake
        qemu-user
        sharutils
        u-boot-tools
        pkg-config
        gcc-arm-linux-gnueabihf
        g++-arm-linux-gnueabihf

    - name: Build fastfetch
      env:
        FASTFETCH_VERSION: "2.62.1"
      run: >
        .github/build.sh

    - name: Commit and push changes
      uses: devops-infra/action-commit-push@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        commit_message: Updated Scripts directory

    - name: Build Custom Database for MiSTer Downloader
      run: >
        sudo chown -R runner .git ;
        set -o pipefail
        && curl --fail --location https://raw.githubusercontent.com/theypsilon/Downloader_DB-Template_MiSTer/main/.github/build_db.py
        | python3 -
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
